aplicacao/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :doacaos
  resources :adocaos
  resources :users
  get "indexs" => "indexs#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

aplicacao/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.admin?
      can :manage, :all
    else
      can [:read, :update], adocao
      can :manage, User
    end
  end
end

aplicacao/app/models/adocao.rb
class Adocao < ApplicationRecord
end

aplicacao/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

aplicacao/app/models/doacao.rb
class Doacao < ApplicationRecord
end

aplicacao/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

aplicacao/app/controllers/adocaos_controller.rb
class AdocaosController < ApplicationController
  before_action :set_adocao, only: [:show, :edit, :update, :destroy]

  # GET /adocaos
  # GET /adocaos.json
  def index
    @adocaos = Adocao.all
  end

  # GET /adocaos/1
  # GET /adocaos/1.json
  def show
  end

  # GET /adocaos/new
  def new
    @adocao = Adocao.new
  end

  # GET /adocaos/1/edit
  def edit
  end

  # POST /adocaos
  # POST /adocaos.json
  def create
    @adocao = Adocao.new(adocao_params)

    respond_to do |format|
      if @adocao.save
        format.html { redirect_to @adocao, notice: 'Adocao was successfully created.' }
        format.json { render :show, status: :created, location: @adocao }
      else
        format.html { render :new }
        format.json { render json: @adocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adocaos/1
  # PATCH/PUT /adocaos/1.json
  def update
    respond_to do |format|
      if @adocao.update(adocao_params)
        format.html { redirect_to @adocao, notice: 'Adocao was successfully updated.' }
        format.json { render :show, status: :ok, location: @adocao }
      else
        format.html { render :edit }
        format.json { render json: @adocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adocaos/1
  # DELETE /adocaos/1.json
  def destroy
    @adocao.destroy
    respond_to do |format|
      format.html { redirect_to adocaos_url, notice: 'Adocao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adocao
      @adocao = Adocao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adocao_params
      params.require(:adocao).permit(:nome, :idade, :cpf, :endereco, :comentario)
    end
end

aplicacao/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

aplicacao/app/controllers/doacaos_controller.rb
class DoacaosController < ApplicationController
  before_action :set_doacao, only: [:show, :edit, :update, :destroy]

  # GET /doacaos
  # GET /doacaos.json
  def index
    @doacaos = Doacao.all
  end

  # GET /doacaos/1
  # GET /doacaos/1.json
  def show
  end

  # GET /doacaos/new
  def new
    @doacao = Doacao.new
  end

  # GET /doacaos/1/edit
  def edit
  end

  # POST /doacaos
  # POST /doacaos.json
  def create
    @doacao = Doacao.new(doacao_params)

    respond_to do |format|
      if @doacao.save
        format.html { redirect_to @doacao, notice: 'Doacao was successfully created.' }
        format.json { render :show, status: :created, location: @doacao }
      else
        format.html { render :new }
        format.json { render json: @doacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doacaos/1
  # PATCH/PUT /doacaos/1.json
  def update
    respond_to do |format|
      if @doacao.update(doacao_params)
        format.html { redirect_to @doacao, notice: 'Doacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @doacao }
      else
        format.html { render :edit }
        format.json { render json: @doacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doacaos/1
  # DELETE /doacaos/1.json
  def destroy
    @doacao.destroy
    respond_to do |format|
      format.html { redirect_to doacaos_url, notice: 'Doacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doacao
      @doacao = Doacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doacao_params
      params.require(:doacao).permit(:nome, :cpf, :idade, :comentario, :raca)
    end
end

aplicacao/app/controllers/indexs_controller.rb
class IndexsController < ApplicationController
end

aplicacao/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:admin, :name)
    end
end

aplicacao/app/helpers/adocaos_helper.rb
module AdocaosHelper
end

aplicacao/app/helpers/application_helper.rb
module ApplicationHelper
end

aplicacao/app/helpers/doacaos_helper.rb
module DoacaosHelper
end

aplicacao/app/helpers/indexs_helper.rb
module IndexsHelper
end

aplicacao/app/helpers/users_helper.rb
module UsersHelper
end

aplicacao/app/views/adocaos/_form.html.erb
<%= form_with(model: adocao, local: true) do |form| %>
  <% if adocao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adocao.errors.count, "error") %> prohibited this adocao from being saved:</h2>

      <ul>
        <% adocao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.text_field :idade %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_area :comentario %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

aplicacao/app/views/adocaos/edit.html.erb
<h1>Editing Adocao</h1>

<%= render 'form', adocao: @adocao %>

<%= link_to 'Show', @adocao %> |
<%= link_to 'Back', adocaos_path %>

aplicacao/app/views/adocaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adocaos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Cpf</th>
      <th>Endereco</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adocaos.each do |adocao| %>
      <tr>
        <td><%= adocao.nome %></td>
        <td><%= adocao.idade %></td>
        <td><%= adocao.cpf %></td>
        <td><%= adocao.endereco %></td>
        <td><%= adocao.comentario %></td>
        <td><%= link_to 'Show', adocao %></td>
        <td><%= link_to 'Edit', edit_adocao_path(adocao) %></td>
        <td><%= link_to 'Destroy', adocao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adocao', new_adocao_path %>

aplicacao/app/views/adocaos/new.html.erb
<h1>New Adocao</h1>

<%= render 'form', adocao: @adocao %>

<%= link_to 'Back', adocaos_path %>

aplicacao/app/views/adocaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @adocao.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @adocao.idade %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @adocao.cpf %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @adocao.endereco %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @adocao.comentario %>
</p>

<%= link_to 'Edit', edit_adocao_path(@adocao) %> |
<%= link_to 'Back', adocaos_path %>

aplicacao/app/views/doacaos/_form.html.erb
<%= form_with(model: doacao, local: true) do |form| %>
  <% if doacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doacao.errors.count, "error") %> prohibited this doacao from being saved:</h2>

      <ul>
        <% doacao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.text_field :idade %>
  </div>

  <div class="field">
    <%= form.label :comentario %>
    <%= form.text_area :comentario %>
  </div>

  <div class="field">
    <%= form.label :raca %>
    <%= form.text_field :raca %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

aplicacao/app/views/doacaos/edit.html.erb
<h1>Editing Doacao</h1>

<%= render 'form', doacao: @doacao %>

<%= link_to 'Show', @doacao %> |
<%= link_to 'Back', doacaos_path %>

aplicacao/app/views/doacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doacaos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Idade</th>
      <th>Comentario</th>
      <th>Raca</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doacaos.each do |doacao| %>
      <tr>
        <td><%= doacao.nome %></td>
        <td><%= doacao.cpf %></td>
        <td><%= doacao.idade %></td>
        <td><%= doacao.comentario %></td>
        <td><%= doacao.raca %></td>
        <td><%= link_to 'Show', doacao %></td>
        <td><%= link_to 'Edit', edit_doacao_path(doacao) %></td>
        <td><%= link_to 'Destroy', doacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doacao', new_doacao_path %>

aplicacao/app/views/doacaos/new.html.erb
<h1>New Doacao</h1>

<%= render 'form', doacao: @doacao %>

<%= link_to 'Back', doacaos_path %>

aplicacao/app/views/doacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @doacao.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @doacao.cpf %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @doacao.idade %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @doacao.comentario %>
</p>

<p>
  <strong>Raca:</strong>
  <%= @doacao.raca %>
</p>

<%= link_to 'Edit', edit_doacao_path(@doacao) %> |
<%= link_to 'Back', doacaos_path %>

aplicacao/app/views/indexs/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>

   <!--- Basic Page Needs
   ================================================== -->
   <meta charset="utf-8">
	<title>Patinhas</title>
	<meta name="description" content="">
	<meta name="author" content="">

   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="css/base.css">
	<link rel="stylesheet" href="css/main.css">
   <link rel="stylesheet" href="css/media-queries.css">
   <%= stylesheet_link_tag    'indexs', media: 'all', 'data-turbolinks-track' => true %>         

   <!-- Script
   =================================================== -->
	<script src="js/modernizr.js"></script>

   <!-- Favicons
	=================================================== -->
	<link rel="shortcut icon" href="favicon.png" >

</head>

<body class="homepage">

   <div id="preloader">
	   <div id="status">
         <img src="images/loader.gif" height="60" width="60" alt="">
         <div class="loader">Loading...</div>
      </div>
   </div>


   <!-- Header
   =================================================== -->
   <header id="main-header">

   	<div class="row header-inner">

	      <div class="logo">
	         <a class="smoothscroll" href="#hero">Patinhas</a>
	      </div>

	      <nav id="nav-wrap">

	         <a class="mobile-btn" href="#nav-wrap" title="Show navigation">
	         	<span class='menu-text'>Show Menu</span>
	         	<span class="menu-icon"></span>
	         </a>
         	<a class="mobile-btn" href="#" title="Hide navigation">
         		<span class='menu-text'>Hide Menu</span>
         		<span class="menu-icon"></span>
         	</a>

	         <ul id="nav" class="nav">
	            <li class="current"><a class="smoothscroll" href="#hero">Home</a></li>
		         <li><a class="smoothscroll" href="#portfolio">Adoção</a></li>
	            <li><a class="smoothscroll" href="#services">Doar</a></li>
	            <li><a class="smoothscroll" href="#about">Entrar</a></li>
	            <li><a class="smoothscroll" href="#journal">Cadastro</a></li>

	         </ul>

	      </nav> <!-- /nav-wrap -->

	   </div> <!-- /header-inner -->

   </header>


   <!-- Hero
   =================================================== -->
   <section id="hero">

		<div class="row hero-content">

			<div class="twelve columns flex-container">

			   <div id="hero-slider" class="flexslider">

				   <ul class="slides">

					   <!-- Slide -->
					   <li>
						   <div class="flex-caption">
								<h1>Salve uma vida. Ele vai te retribuir com todo o coração dele!</h1>
								<p><a class="button stroke smoothscroll" href="#about">Adote!</a></p>
							</div>
					   </li>

					   <!-- Slide -->
					   <li>
							<div class="flex-caption">
								<h1 >Os bichinhos que são adotados parecem realmente entender seu ato de heroísmo.</h1>
								<p><a class="button stroke smoothscroll" href="#portfolio">Adote!</a></p>
							</div>
					   </li>

				   </ul>

			   </div> <!-- .flexslider -->

	      </div> <!-- .flex-container -->

		</div> <!-- .hero-content -->

   </section> <!-- #hero -->


   <!-- Portfolio
   ================================================== -->
   <section id="portfolio">

      <div class="row section-head">

      	<div class="twelve columns">

	         <h1>NOVOS NO SITE<span>.</span></h1>

	         <hr />
	    </div>

      </div>

      <div class="row items">

      	<div class="twelve columns">

            <div id="portfolio-wrapper" class="bgrid-fourth s-bgrid-third mob-bgrid-half group">

          	   <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/cat1.jpg">
                        <div class="overlay"></div>
                        <div class="portfolio-item-meta">
          					      <h5>Alfredo</h5>
                              <p>Macho</p>
          					</div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/cat2.jpg" alt="Hotel Sign">
                        <div class="overlay">
                        	<div class="portfolio-item-meta">
          					      <h5>Luna</h5>
                              <p>Fêmea</p>
          					   </div>
                        </div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid stack item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/cat3.jpg" alt="Beetle">
                        <div class="overlay">
                        	<div class="portfolio-item-meta">
          					      <h5>Esmeralda</h5>
                              <p>Fêmea</p>
          					   </div>
                        </div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/cat4.jpg" alt="Banjo Player">
                        <div class="overlay">
                        	<div class="portfolio-item-meta">
          					      <h5>Algodão</h5>
                              <p>Macho</p>
          					   </div>
                        </div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                     	<img src="images/portfolio/dog1.jpg">
                       	<div class="overlay">
                       		<div class="portfolio-item-meta">
          					      <h5>Batatinha</h5>
                              <p>Macho</p>
          					   </div>
                       	</div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/dog2.jpg" alt="Farmerboy">
                        <div class="overlay">
                        	<div class="portfolio-item-meta">
          					      <h5>Dara</h5>
                              <p>Fêmea</p>
          					   </div>
                        </div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/dog3.jpg" alt="Judah">
                        <div class="overlay">
                        	<div class="portfolio-item-meta">
          					      <h5>Judah</h5>
                              <p>Macho</p>
          					   </div>
                        </div>
                     </a>

                  </div>
          		</div> <!-- /item -->

               <div class="bgrid item">
                  <div class="item-wrap">

                     <a href="portfolio.html">
                        <img src="images/portfolio/dog4.jpg" alt="Embossed Paper">
                        <div class="overlay">
                        	<div class="portfolio-item-meta">
          					      <h5>Pipoca</h5>
                              <p>Macho</p>
          					   </div>
                        </div>
                     </a>

                  </div>
          		</div>  <!-- item end -->

            </div> <!-- /portfolio-wrapper -->

         </div> <!-- /twelve -->

      </div>  <!-- /row -->

   </section> <!-- /Portfolio -->

   <!-- Java Script
   ================================================== -->
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
   <script>window.jQuery || document.write('<script src="js/jquery-1.10.2.min.js"><\/script>')</script>
   <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
   <script src="js/jquery.flexslider.js"></script>
   <script src="js/jquery.fittext.js"></script>
   <script src="js/backstretch.js"></script>
   <script src="js/waypoints.js"></script>
   <script src="js/main.js"></script>

</body>

</html>

aplicacao/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aplicacao</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

aplicacao/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

aplicacao/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

aplicacao/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Admin</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.admin %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

aplicacao/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

aplicacao/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>